name: Workflow PR Only

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pr_job:
    runs-on: ubuntu-latest
    steps:
      - name: PR Message
        run: echo "This workflow triggers ONLY when a Pull Request is created!"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -l
